---
deployment:
  tasks:
    - export DEPLOYPATH=/home/javaenzx/public_html/
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R home $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH